# Generated by Django 4.0.3 on 2022-03-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='views',
            field=models.BigIntegerField(default=0, verbose_name='views_count'),
        ),
    ]
