# Generated by Django 4.0.3 on 2022-03-14 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.commonmodel')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='username')),
                ('role', models.CharField(choices=[('GAMER', 'GAMER'), ('DEVELOPER', 'DEVELOPER'), ('ADMIN', 'ADMIN'), ('DEVELOPER', 'DEVELOPER')], max_length=30, verbose_name='role')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last_login')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.commonmodel', models.Model),
        ),
    ]
